name: MacOS Combined
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  self-host-chez:
    runs-on: macos-latest
    env:
      SCHEME: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "::add-path::$HOME/.idris2/bin"
      - name: Build Idris 2 from bootstrap
        run: make bootstrap && make install && make clean
        shell: bash
      - name: Build self-hosted
        run: make all && make install
        shell: bash
      - name: Test self-hosted
        run: make test INTERACTIVE=''
        shell: bash

  build-bootstrap-racket:
    runs-on: macos-latest
    env:
      IDRIS2_CG: racket
      IDRIS2_TESTS_CG: racket
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          brew install --cask racket
          brew install coreutils
          echo "::add-path::$HOME/.idris2/bin"
      - name: Build from bootstrap
        run: make bootstrap-racket && make install
      - name: Test bootstrapped
        run: make test