name: Nix

on:
  workflow_run:
    workflows: ["Quick check"]
    types:
      - completed

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
    - run: nix-build -A checks.x86_64-linux
