name: Quick check

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - main

env:
  IDRIS2_VERSION: 0.4.0 # For previous-version build
  SCHEME: scheme

jobs:

  from-cached-bootstrap:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          echo "deb http://security.ubuntu.com/ubuntu hirsute universe" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y -t hirsute chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Cache Chez Previous Version
        id: previous-version-cache
        uses: actions/cache@v2
        with:
          path: Idris2-${{ env.IDRIS2_VERSION }}
          key: ${{ runner.os }}-idris2-bootstrapped-hirsute-chez-${{ env.IDRIS2_VERSION }}
      - name : Build previous version
        if: steps.previous-version-cache.outputs.cache-hit != 'true'
        run: |
          wget https://www.idris-lang.org/idris2-src/idris2-$IDRIS2_VERSION.tgz
          tar zxvf idris2-$IDRIS2_VERSION.tgz
          cd Idris2-$IDRIS2_VERSION
          make bootstrap
          cd ..
      - name: Install previous version
        run: |
          cd Idris2-$IDRIS2_VERSION
          make install
          cd ..
      - name: Build current version
        run: |
          make